# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79f65707ca093bc67dcf4076daa4e5769511b413819474496db5edafff0d718849fc6ce29824336dc6dc46d12d1da04fb1db4cee2cf46be12b80a57006b33c7b

test:
  secret_key_base: 777ea4ddc20c733d9b01ada215b85fd6c316a779d728471462df6d3db41e634325cb1822d64981fcb6abcf56c89aaa2e1c797f9e51bbe4dae36b12c30468433b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
